name: PoniArcade_PunishmentsNG
version: 1.10-1
author: AppleDash
description: Punishments for PoniArcade!
main: com.poniarcade.punishmentsng.PoniArcade_PunishmentsNG
depend: [PoniArcade_Core, PoniArcade_Database]
api-version: 1.19
